// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CLDistanceMatrix
NumericMatrix CLDistanceMatrix(const NumericMatrix& mat);
RcppExport SEXP _CMakeRcppTemplate_CLDistanceMatrix(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(CLDistanceMatrix(mat));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP InitCL(void);

static const R_CallMethodDef CallEntries[] = {
    {"_CMakeRcppTemplate_CLDistanceMatrix", (DL_FUNC) &_CMakeRcppTemplate_CLDistanceMatrix, 1},
    {"InitCL", (DL_FUNC) &InitCL, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_CMakeRcppTemplate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
