// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// runifCL
NumericVector runifCL(const int n, const double lower, const double upper);
RcppExport SEXP _OpenCLBayes_runifCL(SEXP nSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(runifCL(n, lower, upper));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP InitCL(void);

static const R_CallMethodDef CallEntries[] = {
    {"_OpenCLBayes_runifCL", (DL_FUNC) &_OpenCLBayes_runifCL, 3},
    {"InitCL", (DL_FUNC) &InitCL, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_OpenCLBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
